#Use the OpenJDK 20 image as the base image
FROM openjdk:20

#Create a new app directory for my app files
RUN mkdir /app

#Copy the app files from host machine to image filesystem
COPY resources/app/

#Set the directory for executing future commands
WORKDIR /

#Run the Main class
CMD java RestaurantApplication

ADD target/spring-boot-docker.jar spring-boot-docker.jar