CREATE TABLE BOARDS(
  TABLE_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  TABLE_NUMBER CHAR(2) NOT NULL UNIQUE,
  CHAIR_INFO CHAR(2) NOT NULL
);

CREATE TABLE CLIENTS(
  CLIENT_ID BIGSERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE RESERVATIONS(
  RESERVATION_ID BIGSERIAL PRIMARY KEY,
  TABLE_ID BIGINT NOT NULL,
  CLIENT_ID BIGINT NOT NULL,
  RES_DATE DATE
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (TABLE_ID) REFERENCES BOARD(TABLE_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
